import { RoleplayScenario } from '../types/index.ts';

export const SCENARIOS: RoleplayScenario[] = [
  {
    id: 'sollicitatie',
    titleNl: 'Sollicitatiegesprek Tech Scale-up',
    titleEn: 'Job Interview (Software Engineering)',
    category: 'Work & Career',
    level: 'B2.1',
    icon: 'Briefcase',
    characterName: 'Bram de Vries',
    characterRole: 'Engineering Manager bij FinTech Amsterdam',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    description: 'Bespreek je technische achtergrond, werkervaring met Java en microservices, en hoe je omgaat met agile teamuitdagingen.',
    briefing: 'Je zit aan tafel met Bram voor een B2-level sollicitatiegesprek. Hij wil weten waarom je naar Nederland bent verhuisd, hoe je communiceert binnen een scrum-team en hoe je complexe technische keuzes onderbouwt.',
    initialMessageNl: 'Goedemorgen! Fijn dat je er bent. Welkom bij ons op kantoor. Laten we beginnen: kun je jezelf kort voorstellen en vertellen wat je aanspreekt in deze functie?',
    learningGoals: [
      'Professioneel verleden presenteren met de voltooid tegenwoordige tijd (perfectum)',
      'Constructief standpunt innemen met B2-connectoren ("enerzijds... anderzijds", "desondanks")',
      'Inversie correct toepassen bij zinnen die beginnen met tijd of reden',
    ],
    recommendedVocab: [
      { nl: 'de werkervaring', en: 'work experience' },
      { nl: 'onderbouwen', en: 'to substantiate / justify' },
      { nl: 'de uitdaging', en: 'challenge' },
      { nl: 'van mening zijn', en: 'to be of the opinion' },
      { nl: 'aansluiten bij', en: 'to align with' },
    ],
  },
  {
    id: 'gemeente_bsn',
    titleNl: 'Gemeenteloket: Inschrijving & BSN',
    titleEn: 'City Hall Registration & BSN',
    category: 'Government & BSN',
    level: 'B1.1',
    icon: 'Building2',
    characterName: 'Anouk Bakker',
    characterRole: 'Ambtenaar Burgerzaken',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    description: 'Regel je adreswijziging, uittreksel BRP of inschrijving bij de gemeente in formeel maar vriendelijk Nederlands.',
    briefing: 'Je hebt een afspraak aan het loket van de gemeente. Je moet je paspoort en huurcontract tonen en uitleggen wanneer je bent verhuisd.',
    initialMessageNl: 'Goedendag, neem gerust plaats. U komt voor de inschrijving op uw nieuwe woonadres, klopt dat? Heeft u uw identiteitsbewijs en huurcontract bij de hand?',
    learningGoals: [
      'Formele beleefdheidsvormen ("u", "zou u", "alstublieft")',
      'Separable verbs ("meenemen", "inleveren", "inschrijven")',
      'Adres- en persoonsgegevens helder formuleren',
    ],
    recommendedVocab: [
      { nl: 'het huurcontract', en: 'rental contract' },
      { nl: 'de verhuizing', en: 'relocation' },
      { nl: 'het uittreksel', en: 'official excerpt' },
      { nl: 'zich inschrijven', en: 'to register oneself' },
    ],
  },
  {
    id: 'huisarts',
    titleNl: 'Spreekuur bij de Huisarts',
    titleEn: 'Doctor’s Appointment',
    category: 'Healthcare',
    level: 'B1.2',
    icon: 'Stethoscope',
    characterName: 'Dr. Maarten van Dijk',
    characterRole: 'Huisarts',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80',
    description: 'Omschrijf fysieke klachten, pijnniveau, medische voorgeschiedenis en vraag om advies of een verwijsbrief.',
    briefing: 'Je voelt je al een week grieperig met aanhoudende hoest en spierpijn. De huisarts stelt gerichte vragen om te bepalen of medicatie of rust nodig is.',
    initialMessageNl: 'Dag! Kom binnen en ga lekker zitten. Waar kan ik je vandaag mee helpen? Waar heb je precies last van?',
    learningGoals: [
      'Lichamelijke sensaties en tijdsduur nauwkeurig omschrijven ("sinds drie dagen", "stekende pijn")',
      'Vragen om verduidelijking over bijwerkingen of dosering',
      'Woordvolgorde in bijzinnen na "omdat" en "als"',
    ],
    recommendedVocab: [
      { nl: 'de klacht', en: 'complaint / symptom' },
      { nl: 'de ontsteking', en: 'inflammation' },
      { nl: 'het recept', en: 'prescription' },
      { nl: 'verwijzen naar', en: 'to refer to (a specialist)' },
    ],
  },
  {
    id: 'inburgering_b1',
    titleNl: 'Inburgering B1 Spreken Examen',
    titleEn: 'Civic Integration B1 Speaking Exam',
    category: 'Inburgering B1',
    level: 'B1.2',
    icon: 'GraduationCap',
    characterName: 'Mevrouw de Jong',
    characterRole: 'Examinator DUO / Inburgering',
    avatar: 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=150&auto=format&fit=crop&q=80',
    description: 'Oefen met echte examenvragen: geef je mening over maatschappelijke stellingen, vergelijk opties en onderbouw met argumenten.',
    briefing: 'In dit gesimuleerde B1-spreekexamen krijg je een stelling over thuiswerken vs. op kantoor werken. Je moet je mening geven en minstens twee argumenten noemen.',
    initialMessageNl: 'Welkom bij het onderdeel Spreken op B1-niveau. De eerste vraag luidt: Veel mensen werken tegenwoordig fulltime thuis. Vind je dat een goede ontwikkeling of juist niet? Geef je mening en leg uit waarom.',
    learningGoals: [
      'Meningsuitingen op B1/B2 niveau ("Volgens mij...", "Daarentegen...", "Het grote voordeel is dat...")',
      'Argumentatiestructuur met "ten eerste", "bovendien", "tot slot"',
      'Geen vermenging van "want" (hoofdzin) en "omdat" (bijzin)',
    ],
    recommendedVocab: [
      { nl: 'de stelling', en: 'statement / proposition' },
      { nl: 'de afweging', en: 'trade-off / consideration' },
      { nl: 'daarentegen', en: 'on the other hand' },
      { nl: 'het standpunt', en: 'point of view' },
    ],
  },
  {
    id: 'huurwoning',
    titleNl: 'Bezichtiging & Huuronderhandeling',
    titleEn: 'Apartment Viewing & Tenancy',
    category: 'Housing',
    level: 'B2.1',
    icon: 'Home',
    characterName: 'Jeroen Kuipers',
    characterRole: 'Verhuurmakelaar',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    description: 'Vraag naar servicekosten, borg, energielabel, onderhoudsafspraken en onderhandel beleefd over opleveringsdatum.',
    briefing: 'Je bezichtigt een 2-kamerappartement in Utrecht. Je wilt weten wat inclusief is (g/w/l), of er parkeervergunningen zijn en wat de opzegtermijn bedraagt.',
    initialMessageNl: 'Welkom! Zoals je ziet heeft de woning veel lichtinval en dubbel glas. Kijk gerust even rond. Heb je al specifieke vragen over de huurvoorwaarden of de servicekosten?',
    learningGoals: [
      'Complexe vragen stellen met indirecte vraagstelling ("Kunt u aangeven of...")',
      'Onderhandelen met voorwaardelijke zinnen ("Als... dan...")',
      'Vastgoedtermen in het Nederlands',
    ],
    recommendedVocab: [
      { nl: 'de servicekosten', en: 'service charges' },
      { nl: 'de waarborgsom', en: 'security deposit' },
      { nl: 'de opzegtermijn', en: 'notice period' },
      { nl: 'het energielabel', en: 'energy rating label' },
    ],
  },
  {
    id: 'gezellige_borrel',
    titleNl: 'Vrijdagmiddagborrel (Vrijmibo)',
    titleEn: 'Friday Casual Café Drinks',
    category: 'Daily Life',
    level: 'B1.1',
    icon: 'Coffee',
    characterName: 'Daan Meijer',
    characterRole: 'Nederlandse Collega',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    description: 'Oefen informele Nederlandse café-gesprekken, humor, weekendplannen en typische uitdrukkingen ("lekker weertje", "nou ja", "proost!").',
    briefing: 'Het is vrijdag 17:00 uur. Je staat met collega Daan aan de bar met een biertje of fris en bitterballen. Hij vraagt naar je weekendplannen.',
    initialMessageNl: 'Hé collega! Proost op het weekend. Heerlijk dat de werkweek erop zit. Zeg, heb je nog leuke plannen voor dit weekend, of ga je lekker uitrusten?',
    learningGoals: [
      'Informeel Nederlands en spreektaalwoorden ("even", "nou", "lekker", "gezellig")',
      'Reageren met empathie en humor',
      'Verleden tijd en toekomende tijd soepel afwisselen',
    ],
    recommendedVocab: [
      { nl: 'gezellig', en: 'cozy / sociable / fun' },
      { nl: 'de bitterbal', en: 'deep-fried savory snack' },
      { nl: 'uitrusten', en: 'to rest / unwind' },
      { nl: 'overwaaien', en: 'to blow over / pass' },
    ],
  },
  {
    id: 'werkoverleg',
    titleNl: 'Sprint Standup & Werkoverleg',
    titleEn: 'Scrum Standup & Team Meeting',
    category: 'Work & Career',
    level: 'B2.2',
    icon: 'MessageSquare',
    characterName: 'Sophie van Leeuwen',
    characterRole: 'Product Owner & Scrum Master',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    description: 'Geef een update over je backend taken, signaleer blokkades, en ga beleefd in discussie over architectuurkeuzes.',
    briefing: 'Tijdens de dagelijkse standup presenteer je de voortgang van de migratie naar Kubernetes en Redis. Sophie vraagt of er afhankelijkheden zijn met het frontend team.',
    initialMessageNl: 'Goedemorgen team! Vishal, laten we bij jou beginnen. Hoe staat het met de API-endpoints en de databaseverbindingen? Lopen we nog op schema voor de sprint-release?',
    learningGoals: [
      'Professioneel nuanceren ("In principe wel, mits...", "Het hangt af van...")',
      'Passieve zinnen en formele werkwoordconstructies ("wordt momenteel geïmplementeerd")',
      'Vakjargon combineren met natuurlijk Nederlands',
    ],
    recommendedVocab: [
      { nl: 'de vertraging', en: 'delay' },
      { nl: 'afstemmen met', en: 'to coordinate / align with' },
      { nl: 'de afhankelijkheid', en: 'dependency' },
      { nl: 'in kaart brengen', en: 'to map out / identify' },
    ],
  },
  {
    id: 'klantenservice',
    titleNl: 'Klantenservice: Garantie & Klacht',
    titleEn: 'Customer Support & Complaint',
    category: 'Daily Life',
    level: 'B1.2',
    icon: 'HelpCircle',
    characterName: 'Sanne Visser',
    characterRole: 'Klantenservicemedewerker',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80',
    description: 'Dien een klacht in over een beschadigd pakket of defect apparaat. Vraag assertief doch vriendelijk om een passende oplossing.',
    briefing: 'Je hebt online een koffiezetapparaat gekocht dat bij levering defect bleek te zijn. Sanne van de klantenservice vraagt naar het ordernummer en de situatie.',
    initialMessageNl: 'Goedemiddag, u spreekt met Sanne van de klantenservice. Wat vervelend om te horen dat er iets mis is met uw bestelling. Zou u mij kunnen vertellen wat er precies aan de hand is?',
    learningGoals: [
      'Beleefd doch duidelijk je rechten als consument benoemen',
      'Tijdsvolgorde en oorzaak-gevolg uitleggen',
      'Vragen om vervanging of terugbetaling ("retourneren", "vergoeden")',
    ],
    recommendedVocab: [
      { nl: 'het defect', en: 'defect / fault' },
      { nl: 'de vergoeding', en: 'compensation / refund' },
      { nl: 'beschadigd', en: 'damaged' },
      { nl: 'oplossen', en: 'to resolve / solve' },
    ],
  },
];
